# Generated by Django 4.2 on 2023-04-18 12:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100, verbose_name='hui')),
                ('eventstartday', models.DateTimeField(default=datetime.datetime(2023, 4, 18, 15, 11, 59, 149401))),
                ('eventendday', models.DateTimeField(default=datetime.datetime(2023, 4, 18, 15, 11, 59, 149401))),
            ],
        ),
    ]
