# Generated by Django 4.2 on 2023-04-18 12:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='name',
        ),
        migrations.AddField(
            model_name='event',
            name='eventdescription',
            field=models.CharField(default='', max_length=500, verbose_name='Описание мероприятия'),
        ),
        migrations.AddField(
            model_name='event',
            name='eventminage',
            field=models.IntegerField(default=0, verbose_name='Минимальный возраст для посещения'),
        ),
        migrations.AddField(
            model_name='event',
            name='eventname',
            field=models.CharField(default='', max_length=100, verbose_name='Название мероприятия'),
        ),
        migrations.AddField(
            model_name='event',
            name='hostemail',
            field=models.EmailField(default='', max_length=100, verbose_name='Почта организатора'),
        ),
        migrations.AddField(
            model_name='event',
            name='hostname',
            field=models.SlugField(default='', max_length=100, verbose_name='Организатор'),
        ),
        migrations.AddField(
            model_name='event',
            name='hosttg',
            field=models.CharField(default='', max_length=100, verbose_name='Телеграм'),
        ),
        migrations.AddField(
            model_name='event',
            name='ticketprice',
            field=models.IntegerField(default=0, verbose_name='Цена билета'),
        ),
        migrations.AlterField(
            model_name='event',
            name='eventendday',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 18, 15, 33, 36, 142777)),
        ),
        migrations.AlterField(
            model_name='event',
            name='eventstartday',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 18, 15, 33, 36, 142777)),
        ),
    ]
