# Generated by Django 4.2 on 2023-04-20 12:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_newuser_password1_remove_newuser_password2_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='evemntpic',
            new_name='eventpic',
        ),
        migrations.AlterField(
            model_name='event',
            name='eventendday',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 20, 15, 36, 31, 849319), verbose_name='Конец мероприятия'),
        ),
        migrations.AlterField(
            model_name='event',
            name='eventstartday',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 20, 15, 36, 31, 849319), verbose_name='Начало мероприятия'),
        ),
    ]
