# Generated by Django 4.2 on 2023-04-20 12:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_rename_evemntpic_event_eventpic_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='eventname',
            new_name='eventtitle',
        ),
        migrations.AlterField(
            model_name='event',
            name='eventendday',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 20, 15, 38, 21, 778683), verbose_name='Конец мероприятия'),
        ),
        migrations.AlterField(
            model_name='event',
            name='eventstartday',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 20, 15, 38, 21, 778683), verbose_name='Начало мероприятия'),
        ),
    ]
