# Generated by Django 3.2.5 on 2023-04-19 07:27

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20230419_0934'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='eventendday',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 19, 10, 27, 22, 633528), verbose_name='Конец мероприятия'),
        ),
        migrations.AlterField(
            model_name='event',
            name='eventstartday',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 19, 10, 27, 22, 633528), verbose_name='Начало мероприятия'),
        ),
        migrations.AlterField(
            model_name='productvideo',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='File', to='main.event'),
        ),
    ]
