# Generated by Django 4.2 on 2023-04-20 13:58

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_event_hostpic_alter_event_eventendday_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='evemntpic',
            field=models.ImageField(default=0, upload_to='imgs/events/', verbose_name='Промо-фото'),
        ),
        migrations.AddField(
            model_name='event',
            name='ticket',
            field=models.ImageField(default=0, upload_to='imgs/events/', verbose_name='Билет'),
        ),
        migrations.AlterField(
            model_name='event',
            name='eventendday',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 20, 16, 58, 53, 916418), verbose_name='Конец мероприятия'),
        ),
        migrations.AlterField(
            model_name='event',
            name='eventstartday',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 20, 16, 58, 53, 916418), verbose_name='Начало мероприятия'),
        ),
        migrations.CreateModel(
            name='RegisterEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100, verbose_name='Имя')),
                ('surname', models.CharField(default='', max_length=100, verbose_name='Фамилия')),
                ('email', models.EmailField(default='', max_length=100, verbose_name='Ваша почта')),
                ('event_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='RegisterEvent', to='main.event')),
            ],
        ),
    ]
