# Generated by Django 4.2 on 2023-04-20 14:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_event_eventendday_alter_event_eventstartday_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='evemntpic',
        ),
        migrations.AlterField(
            model_name='event',
            name='eventendday',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 20, 17, 18, 30, 927883), verbose_name='Конец мероприятия'),
        ),
        migrations.AlterField(
            model_name='event',
            name='eventstartday',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 20, 17, 18, 30, 927883), verbose_name='Начало мероприятия'),
        ),
    ]
