# Generated by Django 4.2 on 2023-04-20 18:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_event_eventplace_alter_event_eventendday_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='eventdescriptionshort',
            field=models.CharField(default='', max_length=80, verbose_name='Краткое описание'),
        ),
        migrations.AddField(
            model_name='event',
            name='eventslogan',
            field=models.CharField(default='', max_length=80, verbose_name='Краткое описание'),
        ),
        migrations.AlterField(
            model_name='event',
            name='eventendday',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 20, 21, 3, 49, 648148), verbose_name='Конец мероприятия'),
        ),
        migrations.AlterField(
            model_name='event',
            name='eventplace',
            field=models.CharField(default='', max_length=200, verbose_name='Место проведения'),
        ),
        migrations.AlterField(
            model_name='event',
            name='eventstartday',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 20, 21, 3, 49, 648148), verbose_name='Начало мероприятия'),
        ),
    ]
