# Generated by Django 4.2 on 2023-04-20 19:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_event_eventdescriptionshort_event_eventslogan_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='ticketprice',
        ),
        migrations.AddField(
            model_name='event',
            name='ticketprice_base',
            field=models.IntegerField(default=0, verbose_name='Цена билета стандарт'),
        ),
        migrations.AddField(
            model_name='event',
            name='ticketprice_coffee',
            field=models.IntegerField(default=0, verbose_name='Цена за кофе в билете'),
        ),
        migrations.AddField(
            model_name='event',
            name='ticketprice_dinner',
            field=models.IntegerField(default=0, verbose_name='Цена за обед в билете'),
        ),
        migrations.AddField(
            model_name='event',
            name='ticketprice_vip',
            field=models.IntegerField(default=0, verbose_name='Цена за vip билет'),
        ),
        migrations.AlterField(
            model_name='event',
            name='eventdescription',
            field=models.CharField(default='', max_length=800, verbose_name='Описание мероприятия'),
        ),
        migrations.AlterField(
            model_name='event',
            name='eventendday',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 20, 22, 26, 39, 342291), verbose_name='Конец мероприятия'),
        ),
        migrations.AlterField(
            model_name='event',
            name='eventslogan',
            field=models.CharField(default='', max_length=80, verbose_name='Слоган'),
        ),
        migrations.AlterField(
            model_name='event',
            name='eventstartday',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 20, 22, 26, 39, 342291), verbose_name='Начало мероприятия'),
        ),
    ]
