# Generated by Django 4.2 on 2023-04-20 19:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_remove_event_ticketprice_event_ticketprice_base_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='eventendday',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 20, 22, 46, 6, 515735), verbose_name='Конец мероприятия'),
        ),
        migrations.AlterField(
            model_name='event',
            name='eventstartday',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 20, 22, 46, 6, 515735), verbose_name='Начало мероприятия'),
        ),
        migrations.AlterField(
            model_name='event',
            name='ticketprice_vip',
            field=models.IntegerField(default=0, verbose_name='Цена за VIP билет'),
        ),
    ]
