# Generated by Django 4.2 on 2023-04-20 21:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_alter_event_eventendday_alter_event_eventstartday_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='registerevent',
            name='ticket_id',
            field=models.CharField(choices=[(1, "Билет 'Standard'"), (2, 'Билет с обедом'), (3, 'Билет с кофе'), (4, "Билет 'VIP'")], default=1, max_length=5),
        ),
        migrations.AlterField(
            model_name='event',
            name='eventendday',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 21, 0, 54, 20, 415846), verbose_name='Конец мероприятия'),
        ),
        migrations.AlterField(
            model_name='event',
            name='eventstartday',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 21, 0, 54, 20, 415846), verbose_name='Начало мероприятия'),
        ),
        migrations.AlterField(
            model_name='event',
            name='ticketprice_coffee',
            field=models.IntegerField(default=0, verbose_name='Цена кофе-билет'),
        ),
        migrations.AlterField(
            model_name='event',
            name='ticketprice_dinner',
            field=models.IntegerField(default=0, verbose_name='Цена обед-билет'),
        ),
    ]
