# Generated by Django 4.2 on 2023-04-20 22:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_registerevent_ticket_id_alter_event_eventendday_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='eventendday',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 21, 1, 4, 19, 721195), verbose_name='Конец мероприятия'),
        ),
        migrations.AlterField(
            model_name='event',
            name='eventstartday',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 21, 1, 4, 19, 721195), verbose_name='Начало мероприятия'),
        ),
    ]
